name: simple-ui-test
run-name: junit-gradle-starter-simple-ui-test
on: [ push ]
jobs:
  test: #job name
    runs-on: ubuntu-latest #where to run
    steps:
      - uses: actions/checkout@v4 #checkout repo
      - uses: actions/setup-java@v4 #setup java
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '18'
      - uses: Xotabu4/selenoid-github-action@v2 #for using selenoid
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub #run string

      #Allure Report
      #Tests history
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #Generate report
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      #Depoy report
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
