name: simple-ui-test
#run-name: junit-gradle-starter-simple-ui-test
on: workflow_dispatch
jobs:
  test: #job name
    runs-on: ubuntu-latest #where to run
    steps:
      - uses: actions/checkout@v3 #checkout repo
      - uses: actions/setup-java@v3 #setup java
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '18'
      - uses: Xotabu4/selenoid-github-action@v2 #for using selenoid
      - run: ./gradlew clean test #run string

      #Allure Report
      #Tests history
      - uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #Generate report
      - uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
      #Depoy report
      - uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history